### ISSUE TITLE
Consider changing license

### ISSUE THREAD

**Issue by mhristache** [moznion/radius-rs#30]
I am looking for a Radius lib for Rust and found this library and [radius-rust](https://crates.io/crates/radius-rust). 

Did a quick check of the supported features and API and I think I prefer `radius-rs` but a copyleft license is a no go for my project.

I also think the current license might prevent more contribution to your lib.

What is your view on changing to a more permissive license like MIT or Apache 2.0?

Thank you

**Comment by moznion** [comment]
Thank you for your suggestion, @mhristache.
Actually, I don't have a strong opinion about the license so I changed that with the MIT license at #31.

And I've just published the new version [v0.3.1](https://github.com/moznion/radius-rs/releases) to crates.io.
