### ISSUE TITLE
No way to set packet identifier

### ISSUE THREAD

**Issue by codertao** [moznion/radius-rs#6]
I'm using the library for radius load testing / pretty much just using the encode/decode functionality.

Right now there's no way to set the identifier of the packet to anything other then the rand value, which is a problem if you're sending multiple packets over the same socket.

**Comment by codertao** [comment]
Similarly, might be useful to offer a decode_unauth for the very very small number of use cases where you just want to try and decode a packet

**Comment by moznion** [comment]
Hello @codertao. Thank you for your suggestion and request.

> Right now there's no way to set the identifier of the packet to anything other then the rand value, which is a problem if you're sending multiple packets over the same socket.

Yes, now it doesn't support giving the arbitrary identifier to a packet. As you mentioned, I also think it would be useful to support the way to do that. Is providing a setter method for an identifier is good for you?

> might be useful to offer a decode_unauth for the very very small number of use cases

I'm sorry I've not been able to understand the actual meaning/demand of `decode_unauth()`. What do you expect the behavior of that?

**Comment by moznion** [comment]
I've just made a pull-request for packet identifier: #7. What do you think about this?

**Comment by codertao** [comment]
Yeah, that'll work for us.

**Comment by codertao** [comment]
And as to decode_unauth: don't worry about it; I misunderstood what the secret being passed to the decode function is for.

**Comment by moznion** [comment]
I've published a new version `v0.1.0` that contains this change to crates.io.
Thank you for your feature request!

I close this issue. If you have another issue, please feel free to open a ticket.
